# An envar that signals to tests we are executing in the CI environment
# Required permissions
# Set job outputs to values from filter step
# For pull requests it's not necessary to checkout the code

name: Modified test other modules
env:
  CONTINUOUS_INTEGRATION: true
  MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
  MAVEN_FAST_INSTALL: -B -V --quiet -T 1C -DskipTests -Dair.check.skip-all --no-transfer-progress
    -Dmaven.javadoc.skip=true
  MAVEN_TEST: -B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true
    --no-transfer-progress --fail-at-end
  RETRY: .github/bin/retry
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      codechange: ${{ steps.filter.outputs.codechange }}
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-changes.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/presto/presto', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |-
          codechange:
            - '!presto-docs/**'
    - run: touch optcd-3.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-changes
        path: /home/runner/inotifywait-log-changes.csv
    name: changes
  test-other-modules:
    runs-on: ubuntu-latest
    needs: changes
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-test-other-modules-${{ github.event.pull_request.number
        }}
      cancel-in-progress: true
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test-other-modules.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/presto/presto', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - run: touch optcd-3.txt
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - run: touch optcd-4.txt
    - name: Cache local Maven repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os }}-maven-2-
    - run: touch optcd-5.txt
    - name: Populate maven cache
      run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress
        && .github/bin/download_nodejs
    - run: touch optcd-6.txt
    - name: Maven Install
      run: |-
        export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
        ./mvnw install ${MAVEN_FAST_INSTALL} -pl '!:presto-docs,!:presto-server,!presto-test-coverage'
    - run: touch optcd-7.txt
    - name: Maven Tests
      run: |-
        ./mvnw test -T 1 ${MAVEN_TEST} -pl '
          !presto-tests,
          !presto-accumulo,
          !presto-cassandra,
          !presto-hive,
          !presto-kudu,
          !presto-docs,
          !presto-server,
          !presto-main,
          !presto-mongodb,
          !presto-spark-package,
          !presto-spark-launcher,
          !presto-spark-testing,
          !presto-spark-base,
          !presto-redis,
          !presto-elasticsearch,
          !presto-orc,
          !presto-thrift-connector,
          !presto-native-execution,
          !presto-test-coverage,
          !presto-iceberg,
          !presto-singlestore'
    - run: touch optcd-8.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test-other-modules
        path: /home/runner/inotifywait-log-test-other-modules.csv
    name: test-other-modules
'on':
- push
- workflow_dispatch
