# An envar that signals to tests we are executing in the CI environment

name: Modified maven checks
env:
  CONTINUOUS_INTEGRATION: true
  MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
  RETRY: .github/bin/retry
jobs:
  maven-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-maven-checks-${{ github.event.pull_request.number
        }}
      cancel-in-progress: true
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-maven-checks.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/presto/presto', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Free Disk Space
      run: |-
        df -h
        sudo apt-get clean
        df -h
    - run: touch optcd-3.txt
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - run: touch optcd-4.txt
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - run: touch optcd-5.txt
    - name: Cache local Maven repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os }}-maven-2-
    - run: touch optcd-6.txt
    - name: Populate maven cache
      run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies  --no-transfer-progress
        -P ci && .github/bin/download_nodejs
    - run: touch optcd-7.txt
    - name: Maven Checks
      run: |-
        export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
        ./mvnw install -B -V -T 1C -DskipTests -Dmaven.javadoc.skip=true --no-transfer-progress -P ci -pl '!presto-test-coverage,!:presto-docs'
    - run: touch optcd-8.txt
    - name: Clean Maven Output
      run: ./mvnw clean -pl '!:presto-server,!:presto-cli,!presto-test-coverage'
    - run: touch optcd-9.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-maven-checks
        path: /home/runner/inotifywait-log-maven-checks.csv
    name: maven-checks
'on':
- push
- workflow_dispatch
